version: "3.9"

services:
  client:
    build: ./client/
    container_name: client
    ports:
      - 3000:80
    environment:
      - REACT_APP_API_PATH=back
  api:
    build: ./api/
    container_name: api
    ports:
      - 8000:8000
  nginx:
    depends_on:
      - client
      - api
    links:
      - client
      - api
    restart: always
    build: ./nginx
    ports:
      - "9000:80"
